CREATE DATABASE IF NOT EXISTS chipmunkdb DEFAULT CHARACTER SET utf8mb4;

USE chipmunkdb;

-- 화면 표시/추가용 데이터 테이블(상품 목록)
CREATE TABLE IF NOT EXISTS items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  price INT NOT NULL,
  stock INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

INSERT INTO items (name, price, stock)
VALUES ('견과류', 3000, 100), ('삼각김밥', 1700, 10)
ON DUPLICATE KEY UPDATE name=VALUES(name);